version: "3.8"

services:
  database:
    container_name: wpbrowser_database
    image: mariadb:10.8
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_USER: ${WORDPRESS_DB_NAME} # Same as db name.
      MYSQL_PASSWORD: ${WORDPRESS_DB_NAME} # Same as db name.
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME} # Same as db name.
    healthcheck:
      test: [ "CMD", "mysqlshow", "-u${WORDPRESS_DB_USER}", "-p${WORDPRESS_DB_PASSWORD}",  "${WORDPRESS_DB_NAME}" ]
      interval: 1s
      timeout: 1s
      retries: 30
    tmpfs:
      - /var/lib/mysql
    ports:
      - "${WORDPRESS_DB_LOCALHOST_PORT}:3306"
