name: CI

on: [push]

jobs:

  lint:
    name: Lint source files for PHP 5.6 compat
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint files
        run: make lint

  sniff:
    name: Sniff source files
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sniff files
        run: make sniff

  test:
    strategy:
      matrix:
        php_version: [ '5.6', '7.3' ]
        codeception_version: [ '2.5', '3.0' ]
    name: Run tests on PHP ${{ matrix.php_version }}, CC ${{ matrix.codeception_version }}
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: whoami
        run: id
      - name: Set src directory hash
        run: echo "::set-env name=SRC_HASH::$(_build/dir_hash.sh src)"
      - name: Cache Composer dependencies
        uses: gerbal/always-cache@v1.0.3
        with:
          path: vendor
          key: composer-${{ matrix.php_version }}-cc-${{ matrix.codeception_version }}-${{ hashFiles('**/composer.json') }}-${{ env.SRC_HASH }}
      - name: Prepare Composer dependencies
        run: test -d vendor || _build/vendor_prepare.sh ${{ matrix.php_version }} ${{ matrix.codeception_version }}
      - name: Dump autoload
        run: _build/dump_autoload.sh ${{ matrix.php_version }}
      - name: Run tests
        env:
          CI_PHP_VERSION: ${{ matrix.php_version }}
          CI_CODECEPTION_VERSION: ${{ matrix.codeception_version }}
        run: make test
