name: Static Analysis
on: [ push ]
jobs:
  lint-on-56:
    name: PHP 5.6 lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: make lint
  phpcs:
    name: phpcs
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: make phpcs
  phpstsan:
    name: phpstan
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          rm composer.json
          mv composer.codecept-4.json composer.json
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.4
          version: 2.2
          args: --ignore-platform-reqs
      - run: make phpstan
